// Generated by Wrangler on Sun Apr 14 2024 14:26:54 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	R2_BUCKET_NAME: "fdgl-proofs";
	R2_BUCKET_PUBLIC_BASEURL: "https://pub-ce953b9238024d7c995c3cabef8f0dc2.r2.dev/";
	MASTER_API_KEY: string;
	JWT_SECRET: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	ACCOUNT_ID: string;
	FDGL: Fetcher;
}
