name = "fdgl-backend"
main = "./src/index.ts"
compatibility_date = "2024-04-05"

[dev]
port = 3000

[vars]
R2_BUCKET_NAME = "fdgl-proofs"
R2_BUCKET_PUBLIC_BASEURL = "https://pub-ce953b9238024d7c995c3cabef8f0dc2.r2.dev/"

[[services]]
binding = "FDGL"
service = "fdgl-core"
entrypoint = "FDGLService"