// Generated by Wrangler on Sat Apr 13 2024 01:44:29 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	R2_BUCKET_NAME: "fdgl-proofs";
	KV: KVNamespace;
	MASTER_API_KEY: string;
	JWT_SECRET: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	ACCOUNT_ID: string;
	R2: R2Bucket;
	DB: D1Database;
}
