// Generated by Wrangler on Sun Apr 14 2024 13:33:24 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	MASTER_API_KEY: string;
	JWT_SECRET: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	ACCOUNT_ID: string;
	FDGL: Fetcher;
}
