// Generated by Wrangler on Sun Apr 21 2024 11:39:44 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	RESPONSE_TYPE: "external";
	DISCORD_API_BASEURL: "https://discord.com/api/v10";
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBKEY: string;
	DISCORD_TESTING_GUILDID: string;
	DISCORD_BOT_TOKEN: string;
	FDGL: Fetcher;
}
