// Generated by Wrangler on Sat May 04 2024 21:29:56 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	RESPONSE_TYPE: "external";
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBKEY: string;
	DISCORD_TESTING_GUILDID: string;
	DISCORD_BOT_TOKEN: string;
	R2: R2Bucket;
	DB: D1Database;
	FDGL: Fetcher;
}
