# Top-level configuration
name = "fdgl-communitybot"
main = "src/index.ts"
compatibility_date = "2024-04-13"

[dev]
port = 3001

[vars]
RESPONSE_TYPE = "external"
DISCORD_API_BASEURL = "https://discord.com/api/v10"

[env.production.vars]
RESPONSE_TYPE = "direct"

[[services]]
binding = "FDGL"
service = "fdgl-core"
entrypoint = "FDGLService"