# Top-level configuration
name = "fdgl-core"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
R2_BUCKET_NAME = "fdgl-proofs"
R2_BUCKET_PUBLIC_BASEURL = "https://pub-ce953b9238024d7c995c3cabef8f0dc2.r2.dev/"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "fdgl-maindb"
database_id = "fb5ec937-8f92-4532-a8c4-9d2d0abc9675"

[[r2_buckets]]
binding = "R2"
bucket_name = "fdgl-proofs"
