// Generated by Wrangler on Sun Apr 14 2024 09:47:30 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	R2_BUCKET_NAME: "fdgl-proofs";
	R2_BUCKET_PUBLIC_BASEURL: "https://pub-ce953b9238024d7c995c3cabef8f0dc2.r2.dev/";
	R2: R2Bucket;
	DB: D1Database;
}
